package tw.com.softleader.e5e5.entity;
// Generated 2015/12/2 �U�� 09:36:37 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", schema = "dbo", catalog = "EEIT82DB")
public class Admin implements java.io.Serializable {
	

	@Override
	public String toString() {
		return "Admin [id=" + id + ", account = "+ account +", authority=" + authority + ", name=" + name + ", password=" + password
				+ ", email = "+email + "]";
	}

	private int id;
	private String account;
	private String authority; 
	private String name;
	private String password;
	private String email;
	private Set<Report> reports = new HashSet<Report>(0);
	private Set<AdminQuestionAndAnswer> adminQuestionAndAnswers = new HashSet<AdminQuestionAndAnswer>(0);

	public Admin() {
	}

	public Admin(int id) {
		this.id = id;
	}

	public Admin(int id,String account, String authority, String name, String password,String email,Set<Report> reports,
			Set<AdminQuestionAndAnswer> adminQuestionAndAnswers) {
		
		this.id = id;
		this.account = account;
		this.authority = authority;
		this.name = name;
		this.password = password;
		this.reports = reports;
		this.email = email;
		this.adminQuestionAndAnswers = adminQuestionAndAnswers;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "account",length = 20)
	public String getAccount(){
		return this.account;
	}
	public void setAccount(String account){
		this.account = account;
	}

	@Column(name = "authority", length = 10)
	public String getAuthority() {
		return this.authority;
	}
	
	public void setAuthority(String authority) {
		this.authority = authority;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Column(name = "email" ,length = 50)
	public String getEmail(){
		return this.email;
	}
	public void setEmail(String email){
		this.email = email;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<AdminQuestionAndAnswer> getAdminQuestionAndAnswers() {
		return this.adminQuestionAndAnswers;
	}

	public void setAdminQuestionAndAnswers(Set<AdminQuestionAndAnswer> adminQuestionAndAnswers) {
		this.adminQuestionAndAnswers = adminQuestionAndAnswers;
	}

}
