package tw.com.softleader.e5e5.entity;
// Generated 2015/12/2 �U�� 07:16:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdminQuestionAndAnswer generated by hbm2java
 */
@Entity
@Table(name = "admin_question_and_answer", schema = "dbo", catalog = "EEIT82DB")
public class AdminQuestionAndAnswer implements java.io.Serializable {

	private int id;
	private Admin admin;
	private User user;
	private String question;
	private String answer;

	public AdminQuestionAndAnswer() {
	}

	public AdminQuestionAndAnswer(int id) {
		this.id = id;
	}

	public AdminQuestionAndAnswer(int id, Admin admin, User user, String question, String answer) {
		this.id = id;
		this.admin = admin;
		this.user = user;
		this.question = question;
		this.answer = answer;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "admin_id")
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "question", length = 100)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "answer", length = 100)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
