package tw.com.softleader.e5e5.entity;
// Generated 2015/12/2 �U�� 07:16:55 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Advertisement generated by hbm2java
 */
@Entity
@Table(name = "advertisement", schema = "dbo", catalog = "EEIT82DB")
public class Advertisement implements java.io.Serializable {

	private int id;
	private String picture;
	private String article;
	private String link;

	public Advertisement() {
	}

	public Advertisement(int id) {
		this.id = id;
	}

	public Advertisement(int id, String picture, String article, String link) {
		this.id = id;
		this.picture = picture;
		this.article = article;
		this.link = link;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "picture")
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "article", length = 100)
	public String getArticle() {
		return this.article;
	}

	public void setArticle(String article) {
		this.article = article;
	}

	@Column(name = "link", length = 50)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
