package tw.com.softleader.e5e5.entity;
// Generated 2015/12/2 �U�� 09:36:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BoardCategoria generated by hbm2java
 */
@Entity
@Table(name = "board_categoria", schema = "dbo", catalog = "EEIT82DB")
public class BoardCategoria implements java.io.Serializable {

	private int id;
	private String name;
	private Date createdDate;
	private Set<Board> boards = new HashSet<Board>(0);

	public BoardCategoria() {
	}

	public BoardCategoria(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public BoardCategoria(int id, String name, Date createdDate, Set<Board> boards) {
		this.id = id;
		this.name = name;
		this.createdDate = createdDate;
		this.boards = boards;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boardCategoria")
	public Set<Board> getBoards() {
		return this.boards;
	}

	public void setBoards(Set<Board> boards) {
		this.boards = boards;
	}

}
