package tw.com.softleader.e5e5.entity;


import java.time.LocalDateTime;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Broadcast generated by hbm2java
 */
@Entity
@Table(name = "broadcast", schema = "dbo", catalog = "EEIT82DB")
public class Broadcast implements java.io.Serializable {

	private int id;
	private User user;
	private String broadcastDescription;
	private String picture;
	private LocalDateTime postTime;

	public Broadcast() {
	}

	public Broadcast(int id) {
		this.id = id;
	}

	public Broadcast(int id, User user, String broadcastDescription, String picture, LocalDateTime postTime) {
		this.id = id;
		this.user = user;
		this.broadcastDescription = broadcastDescription;
		this.picture = picture;
		this.postTime = postTime;
	}

	@Override
	public String toString() {
		return "Broadcast [id=" + id + ", user=" + user + ", broadcastDescription=" + broadcastDescription
				+ ", picture=" + picture + ", postTime=" + postTime + "]";
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "broadcast_description")
	public String getBroadcastDescription() {
		return this.broadcastDescription;
	}

	public void setBroadcastDescription(String broadcastDescription) {
		this.broadcastDescription = broadcastDescription;
	}

	@Column(name = "picture")
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "post_time", length = 23)
	public LocalDateTime getPostTime() {
		return this.postTime;
	}

	public void setPostTime(LocalDateTime postTime) {
		this.postTime = postTime;
	}

}
