package tw.com.softleader.e5e5.entity;
// Generated 2015/12/2 �U�� 09:36:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Broadcast generated by hbm2java
 */
@Entity
@Table(name = "broadcast", schema = "dbo", catalog = "EEIT82DB")
public class Broadcast implements java.io.Serializable {

	private int id;
	private User user;
	private String broadcastDescription;
	private String picture;
	private Date postTime;

	public Broadcast() {
	}

	public Broadcast(int id) {
		this.id = id;
	}

	public Broadcast(int id, User user, String broadcastDescription, String picture, Date postTime) {
		this.id = id;
		this.user = user;
		this.broadcastDescription = broadcastDescription;
		this.picture = picture;
		this.postTime = postTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "broadcast_description")
	public String getBroadcastDescription() {
		return this.broadcastDescription;
	}

	public void setBroadcastDescription(String broadcastDescription) {
		this.broadcastDescription = broadcastDescription;
	}

	@Column(name = "picture")
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "post_time", length = 23)
	public Date getPostTime() {
		return this.postTime;
	}

	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

}
