package tw.com.softleader.e5e5.entity;


import java.time.LocalDateTime;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import tw.com.softleader.e5e5.common.entity.OurEntity;

/**
 * Chat generated by hbm2java
 */
@Entity
@Table(name = "chat", schema = "dbo", catalog = "EEIT82DB")
public class Chat extends OurEntity implements java.io.Serializable {
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private User user;
	@Column(name = "messages", length = 200)
	private String messages;
	@Column(name = "picture")
	private String picture;
	@Column(name = "send_time", length = 23)
	private LocalDateTime sendTime;
	@Column(name = "show_user_info", length = 1)
	private Character showUserInfo;

	public Chat() {
	}

	public Chat(int id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "Chat [id=" + id + ", messages=" + messages + ", picture=" + picture + ", sendTime=" + sendTime
				+ ", showUserInfo=" + showUserInfo + "]";
	}


	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}


	public String getMessages() {
		return this.messages;
	}

	public void setMessages(String messages) {
		this.messages = messages;
	}


	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public LocalDateTime getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(LocalDateTime sendTime) {
		this.sendTime = sendTime;
	}


	public Character getShowUserInfo() {
		return showUserInfo;
	}

	public void setShowUserInfo(Character showUserInfo) {
		this.showUserInfo = showUserInfo;
	}	
	
}
