package tw.com.softleader.e5e5.entity;
// Generated 2015/12/2 �U�� 09:36:37 by Hibernate Tools 4.3.1.Final

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.transaction.Transactional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import tw.com.softleader.e5e5.entity.enums.Grade;
import tw.com.softleader.e5e5.entity.enums.TrueFalse;

/**
 * Exchange generated by hbm2java
 */
@Entity
@Table(name = "exchange", schema = "dbo", catalog = "EEIT82DB")
public class Exchange implements java.io.Serializable {

	private int id;
	private Product productAId;
	private Product productBId;
	private LocalDateTime exchangeTime;
	private LocalDateTime tradeFinishedTime;
	private LocalDateTime gradeTime;
	private Grade grade;
	private TrueFalse tradeStatus;

	public Exchange() {
	}

	public Exchange(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productA_id", referencedColumnName = "id")
	@Transactional
	@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
	public Product getProductByProductAId() {
		return this.productAId;
	}

	public void setProductByProductAId(Product productByProductAId) {
		this.productAId = productByProductAId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productB_id", referencedColumnName = "id")
	@Transactional
	@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
	public Product getProductByProductBId() {
		return this.productBId;
	}

	public void setProductByProductBId(Product productByProductBId) {
		this.productBId = productByProductBId;
	}

	@Column(name = "exchange_time", length = 23)
	public LocalDateTime getExchangeTime() {
		return this.exchangeTime;
	}

	public void setExchangeTime(LocalDateTime exchangeTime) {
		this.exchangeTime = exchangeTime;
	}
	
	@Column(name = "trade_finished_time", length = 23)
	public LocalDateTime getTradeFinishedTime() {
		return tradeFinishedTime;
	}

	public void setTradeFinishedTime(LocalDateTime tradeFinishedTime) {
		this.tradeFinishedTime = tradeFinishedTime;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "grade", length = 10)
	public Grade getGrade() {
		return grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@Column(name = "grade_time", length = 23)
	public LocalDateTime getGradeTime() {
		return gradeTime;
	}

	public void setGradeTime(LocalDateTime gradeTime) {
		this.gradeTime = gradeTime;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "tradeStatus", length = 10)
	public TrueFalse getTradeStatus() {
		return tradeStatus;
	}

	public void setTradeStatus(TrueFalse tradeStatus) {
		this.tradeStatus = tradeStatus;
	}

}
