package tw.com.softleader.e5e5.entity;
// Generated 2015/12/2 �U�� 09:36:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.transaction.Transactional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Exchange generated by hbm2java
 */
@Entity
@Table(name = "exchange", schema = "dbo", catalog = "EEIT82DB")
public class Exchange implements java.io.Serializable {

	private int id;
	private Product productByProductAId;
	private Product productByProductBId;
	private Date exchangeTime;
//	private Set<Product> products = new HashSet<Product>(0);

	public Exchange() {
	}

	public Exchange(int id) {
		this.id = id;
	}

	public Exchange(int id, Product productByProductAId, Product productByProductBId, Date exchangeTime
//			, Set<Product> products
			) {
		this.id = id;
		this.productByProductAId = productByProductAId;
		this.productByProductBId = productByProductBId;
		this.exchangeTime = exchangeTime;
//		this.products = products;
	}
	
	

//	@Override
//	public String toString() {
//		return "Exchange [id=" + id + ", exchangeTime=" + exchangeTime + "]";
//	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productA_id",referencedColumnName="id")
	@Transactional
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Product getProductByProductAId() {
		return this.productByProductAId;
	}

	public void setProductByProductAId(Product productByProductAId) {
		this.productByProductAId = productByProductAId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productB_id",referencedColumnName="id")
	@Transactional
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	public Product getProductByProductBId() {
		return this.productByProductBId;
	}

	public void setProductByProductBId(Product productByProductBId) {
		this.productByProductBId = productByProductBId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exchange_time", length = 23)
	public Date getExchangeTime() {
		return this.exchangeTime;
	}

	public void setExchangeTime(Date exchangeTime) {
		this.exchangeTime = exchangeTime;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exchange")
//	public Set<Product> getProducts() {
//		return this.products;
//	}
//
//	public void setProducts(Set<Product> products) {
//		this.products = products;
//	}

}
