package tw.com.softleader.e5e5.entity;
// Generated 2015/12/14 �U�� 08:24:34 by Hibernate Tools 4.3.1.Final

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.transaction.Transactional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import tw.com.softleader.e5e5.entity.enums.TrueFalse;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", schema = "dbo", catalog = "EEIT82DB")
public class Product implements java.io.Serializable {

	private int id;
	private String name;
	private ProductCategory productCategory;
	private byte[] video;
	private User userId;
	private LocalDateTime postTime;
	private LocalDateTime deadline;
	private String location;
	private String tradeWay;
	private String wishItem;
	private TrueFalse postStatus;
	private Integer clickTimes;

	public Product() {
	}

	public Product(int id) {
		this.id = id;
	}
	
	@Override
	public String toString() {
		return "Product [id=" + id + ", name=" + name + ", video=" + Arrays.toString(video) + ", postTime=" + postTime
				+ ", deadline=" + deadline + ", location=" + location + ", tradeWay=" + tradeWay + ", wishItem="
				+ wishItem + ", postStatus=" + postStatus + ", clickTimes=" + clickTimes + "]";
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", referencedColumnName = "id")
	@Transactional
	@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
	public ProductCategory getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(ProductCategory productCategory) {
		this.productCategory = productCategory;
	}

	@Column(name = "video")
	public byte[] getVideo() {
		return this.video;
	}

	public void setVideo(byte[] video) {
		this.video = video;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", referencedColumnName = "id")
	@Transactional
	@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
	public User getUserByUserId() {
		return this.userId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userId = userByUserId;
	}

	
	@Column(name = "post_time", length = 23)
	public LocalDateTime getPostTime() {
		return this.postTime;
	}

	public void setPostTime(LocalDateTime postTime) {
		this.postTime = postTime;
	}


	@Column(name = "deadline", length = 23)
	public LocalDateTime getDeadline() {
		return this.deadline;
	}

	public void setDeadline(LocalDateTime deadline) {
		this.deadline = deadline;
	}

	@Column(name = "location", length = 50)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "trade_way", length = 20)
	public String getTradeWay() {
		return this.tradeWay;
	}

	public void setTradeWay(String tradeWay) {
		this.tradeWay = tradeWay;
	}

	@Column(name = "wish_item", length = 200)
	public String getWishItem() {
		return this.wishItem;
	}

	public void setWishItem(String wishItem) {
		this.wishItem = wishItem;
	}
	@Enumerated(EnumType.STRING)
	@Column(name = "post_status", length = 10)
	public TrueFalse getPostStatus() {
		return this.postStatus;
	}

	public void setPostStatus(TrueFalse postStatus) {
		this.postStatus = postStatus;
	}

	@Column(name = "click_times")
	public Integer getClickTimes() {
		return this.clickTimes;
	}

	public void setClickTimes(Integer clickTimes) {
		this.clickTimes = clickTimes;
	}

}
