package tw.com.softleader.e5e5.entity;
// Generated 2015/12/13 下午 03:39:44 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import tw.com.softleader.e5e5.common.entity.OurEntity;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name = "product_category", schema = "dbo", catalog = "EEIT82DB")
public class ProductCategory extends OurEntity implements java.io.Serializable {

	@Column(name = "name", nullable = false, length = 20)
	private String name;

	@Override
	public String toString() {
		return "ProductCategory [id=" + id + ", name=" + name + "]";
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
