package tw.com.softleader.e5e5.entity;
// Generated 2015/12/2 �U�� 09:36:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuestionAndAnswer generated by hbm2java
 */
@Entity
@Table(name = "question_and_answer", schema = "dbo", catalog = "EEIT82DB")
public class QuestionAndAnswer implements java.io.Serializable {

	private int id;
	private Product product;
	private String answer;
	private Date editTime;
	private Character isPublic;
	private String question;

	public QuestionAndAnswer() {
	}

	public QuestionAndAnswer(int id) {
		this.id = id;
	}

	public QuestionAndAnswer(int id, Product product, String answer, Date editTime, Character isPublic,
			String question) {
		this.id = id;
		this.product = product;
		this.answer = answer;
		this.editTime = editTime;
		this.isPublic = isPublic;
		this.question = question;
	}

	
	
	@Override
	public String toString() {
		return "QuestionAndAnswer [id=" + id + ", answer=" + answer + ", editTime=" + editTime + ", isPublic="
				+ isPublic + ", question=" + question + "]";
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "answer", length = 200)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edit_time", length = 23)
	public Date getEditTime() {
		return this.editTime;
	}

	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	@Column(name = "is_public", length = 1)
	public Character getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Character isPublic) {
		this.isPublic = isPublic;
	}

	@Column(name = "question", length = 200)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

}
