package tw.com.softleader.e5e5.entity;
// default package
// Generated 2015/12/14 �U�� 08:58:01 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reply generated by hbm2java
 */
@Entity
@Table(name = "reply", schema = "dbo", catalog = "EEIT82DB")
public class Reply implements java.io.Serializable {

	private int id;
	private ForumPicture forumPicture;
	private Thread thread;
	private Date createdDate;
	private String title;
	private String replyContent;
	private Integer floor;
	private Set<Board> boards = new HashSet<Board>(0);
	private Set<ForumPicture> forumPictures = new HashSet<ForumPicture>(0);
	private Set<Report> reports = new HashSet<Report>(0);

	public Reply() {
	}

	public Reply(int id, String title) {
		this.id = id;
		this.title = title;
	}

	public Reply(int id, ForumPicture forumPicture, Thread thread, Date createdDate, String title, String replyContent,
			Integer floor, Set<Board> boards, Set<ForumPicture> forumPictures, Set<Report> reports) {
		this.id = id;
		this.forumPicture = forumPicture;
		this.thread = thread;
		this.createdDate = createdDate;
		this.title = title;
		this.replyContent = replyContent;
		this.floor = floor;
		this.boards = boards;
		this.forumPictures = forumPictures;
		this.reports = reports;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "picture_id")
	public ForumPicture getForumPicture() {
		return this.forumPicture;
	}

	public void setForumPicture(ForumPicture forumPicture) {
		this.forumPicture = forumPicture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "thread_id")
	public Thread getThread() {
		return this.thread;
	}

	public void setThread(Thread thread) {
		this.thread = thread;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "title", nullable = false, length = 20)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "reply_content", length = 3000)
	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	@Column(name = "floor")
	public Integer getFloor() {
		return this.floor;
	}

	public void setFloor(Integer floor) {
		this.floor = floor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reply")
	public Set<Board> getBoards() {
		return this.boards;
	}

	public void setBoards(Set<Board> boards) {
		this.boards = boards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reply")
	public Set<ForumPicture> getForumPictures() {
		return this.forumPictures;
	}

	public void setForumPictures(Set<ForumPicture> forumPictures) {
		this.forumPictures = forumPictures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reply")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

}
