package tw.com.softleader.e5e5.entity;
// Generated 2015/12/14 �U�� 06:49:36 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "report", schema = "dbo", catalog = "EEIT82DB")
public class Report implements java.io.Serializable {

	private int id;
	private Product product;
	private String article;
	private Character isPassed;
	private Date reportTime;
	private Integer reporterId;
	private Integer adminId;
	private Integer threadId;
	private Integer replyId;

	public Report() {
	}

	public Report(int id) {
		this.id = id;
	}

	public Report(int id, Product product, String article, Character isPassed, Date reportTime, Integer reporterId,
			Integer adminId, Integer threadId, Integer replyId) {
		this.id = id;
		this.product = product;
		this.article = article;
		this.isPassed = isPassed;
		this.reportTime = reportTime;
		this.reporterId = reporterId;
		this.adminId = adminId;
		this.threadId = threadId;
		this.replyId = replyId;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "article", length = 200)
	public String getArticle() {
		return this.article;
	}

	public void setArticle(String article) {
		this.article = article;
	}

	@Column(name = "is_passed", length = 1)
	public Character getIsPassed() {
		return this.isPassed;
	}

	public void setIsPassed(Character isPassed) {
		this.isPassed = isPassed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "report_time", length = 23)
	public Date getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	@Column(name = "reporter_id")
	public Integer getReporterId() {
		return this.reporterId;
	}

	public void setReporterId(Integer reporterId) {
		this.reporterId = reporterId;
	}

	@Column(name = "admin_id")
	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	@Column(name = "thread_id")
	public Integer getThreadId() {
		return this.threadId;
	}

	public void setThreadId(Integer threadId) {
		this.threadId = threadId;
	}

	@Column(name = "reply_id")
	public Integer getReplyId() {
		return this.replyId;
	}

	public void setReplyId(Integer replyId) {
		this.replyId = replyId;
	}

}
