package tw.com.softleader.e5e5.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.transaction.Transactional;

/**
 * UserOwner generated by hbm2java
 */
@Entity
@Table(name = "[user_owner]", schema = "dbo", catalog = "EEIT82DB")
public class UserOwner implements java.io.Serializable {

	private int id;
	private Board board;
	private Integer userId;

	public UserOwner() {
	}

	public UserOwner(int id) {
		this.id = id;
	}

	public UserOwner(int id, Board board, Integer userId) {
		this.id = id;
		this.board = board;
		this.userId = userId;
	}

	
	
	
	
	
	
	
	@Override
	public String toString() {
		return "UserOwner [id=" + id + ", board=" + board + ", userId=" + userId + "]";
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "board_id")
	@Transactional
	public Board getBoard() {
		return this.board;
	}

	public void setBoard(Board board) {
		this.board = board;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
