package tw.com.softleader.e5e5.entity;
// Generated 2015/12/2 �U�� 09:36:37 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.transaction.Transactional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import tw.com.softleader.e5e5.common.entity.OurEntity;

/**
 * UserBanList generated by hbm2java
 */
@Entity
@Table(name = "user_ban_list", schema = "dbo", catalog = "EEIT82DB")
public class UserBanList  extends OurEntity implements java.io.Serializable {

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_a_id",referencedColumnName="id")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private User userAId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_b_id",referencedColumnName="id")
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private User userBId;



	public UserBanList() {
	}

	public UserBanList(int id) {
		this.id = id;
	}


	public User getUserByUserAId() {
		return this.userAId;
	}

	public void setUserByUserAId(User userByUserAId) {
		this.userAId = userByUserAId;
	}


	public User getUserByUserBId() {
		return this.userBId;
	}

	public void setUserByUserBId(User userByUserBId) {
		this.userBId = userByUserBId;
	}

}
